# Generated by Django 5.1.3 on 2025-01-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=255)),
                ("temperature", models.FloatField()),
                ("weather_description", models.CharField(max_length=255)),
                ("weather_icon", models.URLField()),
                ("wind_speed", models.FloatField()),
                ("humidity", models.FloatField()),
                ("date_searched", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date_searched"],
            },
        ),
    ]
